version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: news-app-backend
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - whatsapp-auth:/app/backend/auth_info_baileys
    networks:
      - apps

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: news-app-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - apps

volumes:
  whatsapp-auth:

networks:
  apps:
    external: true
